"""initial_schema

Revision ID: 01869554d538
Revises: 
Create Date: 2026-03-28 18:17:04.135900
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '01869554d538'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('agent_state', sa.String(length=20), nullable=False),
    sa.Column('original_decision', sa.String(length=10), nullable=False),
    sa.Column('final_decision', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portfolio_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_passed', sa.Boolean(), nullable=False),
    sa.Column('degraded_context', sa.Boolean(), nullable=False),
    sa.Column('evidence_pack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('signal_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alert_latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exec_logs_created', 'agent_execution_logs', ['created_at'], unique=False)
    op.create_index('ix_exec_logs_signal_id', 'agent_execution_logs', ['signal_id'], unique=False)
    op.create_index('ix_exec_logs_tenant', 'agent_execution_logs', ['tenant_id'], unique=False)
    op.create_index('ix_exec_logs_ticker', 'agent_execution_logs', ['ticker'], unique=False)
    op.create_index('ix_exec_logs_user_id', 'agent_execution_logs', ['user_id'], unique=False)
    op.create_table('market_knowledge_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'ticker', name='uq_knowledge_content_ticker')
    )
    op.create_index('ix_knowledge_ticker_date', 'market_knowledge_base', ['ticker', 'published_at'], unique=False)
    op.create_index(op.f('ix_market_knowledge_base_ticker'), 'market_knowledge_base', ['ticker'], unique=False)
    op.create_table('portfolio_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_active_symbol', 'portfolio_positions', ['symbol'], unique=False, postgresql_where='is_active = true')
    op.create_index('ix_positions_symbol', 'portfolio_positions', ['symbol'], unique=False)
    op.create_index('ix_positions_user_symbol', 'portfolio_positions', ['user_id', 'symbol'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('holdings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_idempotency_key'), 'processed_events', ['idempotency_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_state', sa.String(length=20), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('policy_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portfolio_mode', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_agent_state', 'users', ['agent_state'], unique=False)
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_index('ix_users_agent_state', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_processed_events_idempotency_key'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_positions_user_symbol', table_name='portfolio_positions')
    op.drop_index('ix_positions_symbol', table_name='portfolio_positions')
    op.drop_index('ix_positions_active_symbol', table_name='portfolio_positions', postgresql_where='is_active = true')
    op.drop_table('portfolio_positions')
    op.drop_index(op.f('ix_market_knowledge_base_ticker'), table_name='market_knowledge_base')
    op.drop_index('ix_knowledge_ticker_date', table_name='market_knowledge_base')
    op.drop_table('market_knowledge_base')
    op.drop_index('ix_exec_logs_user_id', table_name='agent_execution_logs')
    op.drop_index('ix_exec_logs_ticker', table_name='agent_execution_logs')
    op.drop_index('ix_exec_logs_tenant', table_name='agent_execution_logs')
    op.drop_index('ix_exec_logs_signal_id', table_name='agent_execution_logs')
    op.drop_index('ix_exec_logs_created', table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    # ### end Alembic commands ###
