"""
Video Engine Schemas — Typed request/response models for AI Market Video Engine.
"""

from __future__ import annotations

from typing import Optional, List
from enum import Enum

from pydantic import BaseModel, Field


class VideoTheme(str, Enum):
    MARKET_WRAP = "market_wrap"
    EARNINGS = "earnings"
    SECTOR_ROTATION = "sector_rotation"
    STOCK_FOCUS = "stock_focus"


class VideoGenerateRequest(BaseModel):
    """Request body for video generation."""
    ticker: str = Field(..., description="Primary ticker for the video")
    duration_sec: int = Field(45, ge=30, le=90, description="Target video duration 30-90 seconds")
    theme: VideoTheme = Field(VideoTheme.MARKET_WRAP, description="Video style theme")
    additional_tickers: List[str] = Field(default_factory=list, description="Extra tickers to mention")


class VideoGenerateResponse(BaseModel):
    """Response for video generation — returned immediately with job_id."""
    job_id: str
    status: str = Field("processing", description="processing | completed | failed")
    video_url: Optional[str] = Field(None, description="URL to download video when ready")
    filename: Optional[str] = None
    duration_sec: int = 45


class VideoStatusResponse(BaseModel):
    """Response for video status check."""
    job_id: str
    status: str = Field(description="processing | completed | failed")
    video_url: Optional[str] = None
    filename: Optional[str] = None
    duration_sec: int = 45
    progress_pct: int = Field(0, ge=0, le=100)
    error: Optional[str] = None


class ScriptScene(BaseModel):
    """A single scene in the video script."""
    scene_id: int
    narration: str = Field(description="Text to be spoken by TTS")
    visual_cue: str = Field(description="What chart/visual to display")
    duration_sec: float = Field(5.0, description="Approximate scene duration")


class VideoScript(BaseModel):
    """Full video script generated by LLM."""
    title: str
    ticker: str
    opening_line: str
    scenes: List[ScriptScene]
    closing_line: str
    total_narration: str = Field("", description="Full concatenated narration text")
